#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

# Copyright 2019, Richard Lowe.

CPPFLAGS =	-I. -I$(SRCDIR) -I$(SRCDIR)/common \
	-I$(SGSHOME)/include -I$(SGSHOME)/include/$(MACH) \
	$(CPPFLAGS.native) -I$(ELFCAP) -DNATIVE_BUILD \
	$(COMPAT_CPPFLAGS)

#
# The host link-editor is not illumos' -- it understands neither illumos ld's
# options nor its mapfiles.  (That is the whole reason this native build
# exists: to produce an ld that does.)  Empty the macros the shared makefiles
# feed into LDFLAGS and DYNFLAGS, rather than trying to filter them back out.
#
BDIRECT=
BLOCAL=
BREDUCE=
ZDEFS=
ZDIRECT=
ZIGNORE=
ZINTERPOSE=
ZLAZYLOAD=
ZLOADFLTR=
ZNOLAZYLOAD=
ZNOLDYNSYM=
ZRECORD=
ZREDLOCSYM=
ZTEXT=
ZVERBOSE=
ZASSERTDEFLIB=
ZGUIDANCE=
ZFATALWARNINGS=
ZASLR=
LDCHECKS=
NATIVE_LIBS=

# cw turns $(SAVEARGS) into gcc's -msave-args, which only illumos' gcc has.
SAVEARGS=

MAPFILE.NED=
MAPFILE.PGA=
MAPFILE.NES=
MAPFILE.FLT=
MAPFILE.NGB=
MAPFILE.INT=
MAPFILES=
DYNFLAGS_MAPFILES=

# -ulink_ver_string exists to drag libconv's vernote.o in; that object is
# generated by illumos-only tooling and carries nothing ld needs.
VERSREF=

#
# There is no CTF, no mcs and no strip for these objects: they are build
# tools, not deliverables.  Reduce every post-processing step to a no-op --
# and to `:' rather than nothing, since the shared makefiles splice these
# into compound `a ; b' command lines.
#
CTFCONVERT_POST=	:
CTFMERGE_POST=		:
POST_PROCESS_O=		:
POST_PROCESS_S_O=	:
POST_PROCESS_CC_O=	:
POST_PROCESS_A=		:
POST_PROCESS_SO=	:
POST_PROCESS=		:
PROCESS_CTF=		:
STRIP_STABS=		:

#
# lib/Makefile.lib builds DYNFLAGS out of the macros emptied above, and the
# cmd/sgs library makefiles then append illumos ld's `-R' (which GNU ld spells
# `-rpath').  Restate it rather than patch it up piecemeal.  $$ORIGIN survives
# because the loader, not the link-editor, expands it, and GNU ld only has to
# copy the string through.
#
DYNFLAGS=	$(HSONAME) -Wl,-rpath,'$$ORIGIN'
